name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore source/ObjectTextTokens.sln
    - name: Build
      run: dotnet build source/ObjectTextTokens.sln --no-restore --configuration Release
    - name: Test
      run: dotnet test source/ObjectTextTokens.Tests/ObjectTextTokens.Tests.csproj --no-build --configuration Release --verbosity normal
    - name: Pack with dotnet
      run: dotnet pack source/ObjectTextTokens/ObjectTextTokens.csproj --output nuget-packages --configuration Release  
    - name: Push with dotnet
      run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate  
